services:
  silversea-chatbot:
    build: .
    platform: linux/amd64
    image: silversea-chatbot
    container_name: silversea-chatbot
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/app
    working_dir: /app